export interface ICompany {
    id: string;
    nameCompany: string;
    NIT: string;
    verificationDigit: string;
    profilePicture?: string;
    logo?: string;
    commercialName?: string;
    userType: 'Company';
    typeRole: 'CEO' | 'Moderador de atención al cliente' | 'CTO' | 'Desarrollador de software' | 'Financiador de programas' | 'Superadmin' | 'Administrador' | 'Vendedor' | 'Cajero' | 'Operativo' | 'Contador';
    nameCompanyLeader: string;
    lastNameCompanyLeader: string;
    typeDocumentIdLeaderCompany: 'Cédula de Ciudadanía' | 'Cédula de Extranjería' | 'Pasaporte';
    documentIdLeaderCompany: string;
    economicSector:  'Agricultura' | 'Manufactura' | 'Comercio' | 'Servicios' | 'Construcción' | 'Turismo' | 'Otro';
    codeCiiu: string;
    email: string;
    password: string;
    phone: string;
    department: 'Bogotá D.C.' | 'Amazonas' | 'Antioquia' | 'Arauca' | 'Atlántico' | 'Bolívar' | 'Boyacá' | 'Caldas' | 'Caquetá' | 'Casanare' | 'Cauca' | 'Cesar' | 'Chocó' | 'Córdoba' | 'Cundinamarca' | 'Guainía' | 'Guaviare' | 'Huila' | 'La Guajira' | 'Magdalena' | 'Meta' | 'Nariño' | 'Norte de Santander' | 'Putumayo' | 'Quindío' | 'Risaralda' | 'San Andrés y Providencia' | 'Santander' | 'Sucre' | 'Tolima' | 'Valle del Cauca' | 'Vaupés' | 'Vichada';
    city: string;
    codeDane: string;
    subregionCodeDane: string;
    address: string;
    numberEmployees?: number;
    passwordResetCode?: string;
    passwordResetCodeDate?: Date;    
    loginAttempts?: number;
    isBlocked?: boolean;
    unlockCode?: string;
    expiresAt?: Date;
    projectFunder?: string;
    applicationPassword?: string;
    isAceptedConditions: boolean;
};